# for local developments, ports mapped to host so local fluent-bit can connect
version: '2.1'

services:
  testlog1:
    image: alpine:3.6
    volumes:
      - ./log:/var/log
    entrypoint: /bin/sh
    command: ["-c", "while true; do date >> /var/log/testlog1.log; sleep 1; done"]

  zookeeper:
    image: solsson/zookeeper
  kafka:
    image: solsson/kafka-persistent:0.10.1.0
    links:
      - zookeeper
    ports:
      - 9092:9092

  kafka-topic-client:
    image: solsson/kafka-topic-client
    links:
      - zookeeper
      - kafka
    environment:
      TOPIC_NAME: "logs"

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    #volumes:
    #  - ./data/es1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
